<?php
########################################################################
# Extension Manager/Repository config file for ext: "extbasenews"
#
# Auto generated by Extbase Kickstarter 2010-12-20
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Extbase tt_news',
	'description' => 'Extbase version of tt_news',
	'category' => 'plugin',
	'author' => 'Philipp Gampe',
	'author_email' => 'typo3.dev@philippgampe.info',
	'author_company' => '',
	'shy' => '',
	'dependencies' => 'extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'test',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>